### ISSUE TITLE
117 Persons in Mueller Report not seen in TrumpWorld

### ISSUE THREAD

**Issue by datapol** [BuzzFeedNews/everything#49]
Thank you for putting your data on-line in a searchable format.

Of the 174 'Persons' in the Mueller Report, I only see 53 matched with the people you have in TrumpWorld. Why are there 117 people in the Mueller Report NOT mentioned in TrumpWorld? Are they mentioned in some other searchable Buzz database?

Attached are the people I see in the Mueller Report that are NOT mentioned in TrumpWorld:.

[mueller1_buzz0.txt](https://github.com/BuzzFeedNews/everything/files/3204810/mueller1_buzz0.txt)

Thank you again for your great work.

**Comment by datapol** [comment]
Also, where is Leonard Leo mentioned? I do not see him in the TrumpWorld database. Is there another database that connects him to Trump?

**Comment by jsvine** [comment]
Hi @datapol, and very glad to see that our work has piqued your interest. Unfortunately, TrumpWorld is [no longer being updated](https://github.com/BuzzFeedNews/trumpworld), and hasn't been for a couple of years now, which explains why it does not contain information in the Mueller report. You are, however, more than welcome to "fork" the project and add that information to your own copy of the data.
